# Generated by Django 4.2.2 on 2023-06-23 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codebusters', '0002_rename_quote_id_solve_puzzle_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='puzzle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='codebusters.puzzle'),
        ),
    ]
