# Generated by Django 4.2.2 on 2023-06-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebusters', '0004_alter_solve_solve_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='alphabet',
            field=models.CharField(default='ABCDEFGHIJKLMNOPQRSTUVWXYZ', max_length=64),
            preserve_default=False,
        ),
    ]
